### ISSUE TITLE
Design a database

### ISSUE THREAD

**Issue by chodds** [cockatoos/sprint-board#14]

**Comment by ansonmiu0214** [comment]
Planned Firestore collections:

1. documents
   * id: string, autogenerated?
   * text: string, e.g. `hello world`
   * phraseIndexes: list[ string ], e.g. `[ 0-10, 10-13, ] `
2. users
    * userId: string, autogenerated?
3. clarity_scores
    * userId
    * datetime
    * correctWords: int
    * totalWords: int
4. accent_scores
    * userId
    * datetime
    * accentScore: float/decimal

**Comment by ansonmiu0214** [comment]
Addressed by cockatoos/cockatoos-app#10
