### ISSUE TITLE
Implement NGRX state management for user score data

### ISSUE THREAD

**Issue by neshang** [cockatoos/sprint-board#24]
Add in ngrx dependency and create store for historical score data

**Comment by ansonmiu0214** [comment]
Some of the ngrx boilerplate (e.g. folder structure for states/reducers/actions/effects/selectors) are covered in cockatoos/cockatoos-app#6

**Comment by ansonmiu0214** [comment]
> Some of the ngrx boilerplate (e.g. folder structure for states/reducers/actions/effects/selectors) are covered in [cockatoos/cockatoos-app#6](https://github.com/cockatoos/cockatoos-app/pull/6)

Changes merged to main branch

**Comment by ansonmiu0214** [comment]
Resolved by cockatoos/cockatoos-app#13
