### ISSUE TITLE
Wireframe - design the accent scoring improvement chart

### ISSUE THREAD

**Issue by ansonmiu0214** [cockatoos/sprint-board#7]
How to track the accent score and "word score" over time?

**Comment by neshang** [comment]
https://docs.google.com/drawings/d/1vq7XbGCkd9MM4ATrEHNnTMTg2ptHz7j8d-VQhkL1dps/edit?usp=sharing

**Comment by ansonmiu0214** [comment]
@neshang General idea looks good + shows the required info very clearly. Like you mentioned, if we decide on what data this component should display, we can always improve how it is displayed (e.g. different charts, different numbers) in the future.

```typescript
@Input
Historical Data

@Input
Current Accent Score

@Input
Current Word Accuracy Score
```

Assume 'Historical Data' = `list[ tuple[ date, accentScore, wordAccuracyScore ] ] `:
we won't explicitly need to pass in 'current accent score' and 'current word accuracy score', since that can be derived from 'Historical Data'?

And as a future feature, could also let the user filter based on a date range (assuming they use the app for a long time).
